### ISSUE TITLE
Ingest Persian translation, alignments and other annotations for Iliad

### ISSUE THREAD

**Issue by jacobwegner** [scaife-viewer/beyond-translation-site#10]
This issue tracks integrating the translation Farnoosh has created into the Beyond Translation site.

A preview instance is available at:

https://beyond-translation-persian-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.shamsian-far1:1.2274106-1.2274106e

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/629062/135321766-4fc67a4a-c321-4cce-b22b-5296a6275e9c.png">

and the alignment of the first six sentences can be found at:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/629062/135322936-76d76625-b360-4396-821d-44701bf9e02f.png">

https://beyond-translation-persian-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.shamsian-far1:1.2274106-1.2274106e?mode=alignments&rs=urn%3Acite2%3Ascaife-viewer%3Aalignment.v1%3Ailiad-greek-farsi-word-alignment-32b47d02381146aeaf2eff5786e52400

## TODOs
- [x] Ingest [Farnoosh Homer without the line-breaks](https://docs.google.com/document/d/1Tx_WKF29_dhpSHaEst7-ttOmkJuR_PTLZ4_nRuMy3GQ/edit)
- [ ] Align the Persian to the Greek via [Iliad one UD and Persian alignment together ۴۰۷  ](https://docs.google.com/spreadsheets/d/165AyncuQRUrjfDGB-2yI3dKS9UwDBgF-421Z6f5fpE4/edit#gid=1275983115) (_jn progress_)
- [ ] Import glosses (similar to how the "Word List" widget works in the Greek)
- [ ] Integrate with "Modular Grammar for Annotation" (likely using the dictionary entry data model)
- [ ] Use [Iliad one UD and Persian alignment together ۴۰۷  ](https://docs.google.com/spreadsheets/d/165AyncuQRUrjfDGB-2yI3dKS9UwDBgF-421Z6f5fpE4/edit#gid=1275983115)  to populate syntax tree annotations (either with Greek as the primary and Persian glosses or vice versa; Pedallion tree work would be prior art, c.f. https://scaife-stack-br-pedalion-synta.herokuapp.com/

cc: @gregorycrane @farnoosh-shamsian

**Comment by jacobwegner** [comment]
Sentence alignment between Persian / Greek for Iliad 1:

https://beyond-translation-persian-dev.herokuapp.com/reader/urn:cts:greekLit:tlg0012.tlg001.shamsian-far1:1.s1-1.s6?mode=alignments&rs=urn%3Acite2%3Ascaife-viewer%3Aalignment.v1%3Ailiad-greek-farsi-sentence-alignment

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/629062/142506875-29ade6b6-9f87-40a8-9e34-b53817338dc9.png">
